/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export default function Stegosaur(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('./stegosaurs_SStenops.glb');
    const { actions } = useAnimations(animations, group);

    // Set animation controls
    const { animationName } = useControls('animations', {
        animationName: { options: Object.keys(actions), value: 'walk1' }
    })

    // Set model animation on the first frame (or when animationName changes)
    useEffect(() => {
        const animation = actions[animationName]
        animation
            .reset()
            .fadeIn(.5)
            .play()

        // Remove the previous animation when we changes animationName
        return () => {
            animation.fadeOut(.5)
        }
    }, [animationName]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="stego_rigging">
                    <primitive object={nodes.hipRoot} />
                    <skinnedMesh
                        name="stegoEyeLeft"
                        geometry={nodes.stegoEyeLeft.geometry}
                        material={materials.stegosaurusMatt}
                        skeleton={nodes.stegoEyeLeft.skeleton}
                    />
                    <skinnedMesh
                        name="stegoEyeRight"
                        geometry={nodes.stegoEyeRight.geometry}
                        material={materials.stegosaurusMatt}
                        skeleton={nodes.stegoEyeRight.skeleton}
                    />
                    <skinnedMesh
                        name="stegosaurusLowPoly"
                        geometry={nodes.stegosaurusLowPoly.geometry}
                        material={materials.stegosaurusMatt}
                        skeleton={nodes.stegosaurusLowPoly.skeleton}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('./stegosaurs_SStenops.glb');
