/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cedeon (https://sketchfab.com/cedeon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stone-pillar-4b74c340d1bf47ccad35b57deb78b58a
title: Stone Pillar
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function StonePillar(props) {
  const { nodes, materials } = useGLTF('./stone_pillar.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Pillar_low_Material_0"
        castShadow
        // receiveShadow
        geometry={nodes.Pillar_low_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload('./stone_pillar.glb');
